### PR TITLE
Redesign the layout of the site

### PR DESCRIPTION
**Pull request by mudge**
screen shot 2016-07-17 at 17 10 27

Gone is our beloved cellular automaton, replaced with a photograph from one of our meetings (we could choose another which is better representation of the meetings).

Simplify fonts to Roboto for headings and the best system sans-serif we can find.

With the automaton gone, remove the "rule"-based copy in favour of an distinct code of conduct section and re-order the sections on the homepage in terms of likely interest.

### CODE REVIEW

**Comment by tomstuart** [comment]
This looks like a big improvement. Thanks @mudge!

I wanted to check it out locally, but it seems to be missing `/images/solution-tree.jpg`. Could you add it?

**Comment by mudge** [comment]
@tomstuart: my mistake, should be present now.

**Comment by mudge** [comment]
As we use it as a logo across various places, perhaps we should restore the cellular automaton but as a square in the header (perhaps removing the interactive rules)?

**Comment by tuzz** [comment]
👍  from me. We could add the cellular automaton back in a separate pull request as it would be great to reap the benefits sooner.

**Pull request merged**
